name: Latest Blog Posts Workflow
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ranjitmaity95"
          max_post_count: 5
          template: "📝 [$title]($url)"
          commit_message: "Updated README with latest blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
